### DISCUSSION TITLE
Use of safe-control-gym to validate other control algorithms

### DISCUSSION THREAD

**Discussion by prabhatkmishra** [utiasDSL/safe-control-gym#121] [Q&A]
Hello,

The safe-control-gym package has three environments (cartpole, 1d quadcopter, 2d quadcopter), two tasks (tracking, stabilization) and twelve controller algorithms. I have the following question:

How can I run linear MPC on 2d quadcopter?

Is there any tutorial (or authors planning to make one) to use the safe-control-gym package for other control algorithms?

**Comment by adamhall** [comment]
Hi @prabhatkmishra,

Your question slipped under the radar. Sorry about that. We are still working on tutorials for more of the controllers.

You could run the 2D quadrotor to track a circle reference trajectory on the current `main` branch by creating the following two files in the `experiments` directory:

1. `linear_mpc_test.py`
```
from functools import partial

from safe_control_gym.utils.registration import make
from safe_control_gym.utils.configuration import ConfigFactory

if __name__ == "__main__":
    fac = ConfigFactory()
    config = fac.merge()
    # Create environment.
    env_func = partial(make,
                       config.task,
                       seed=config.seed,
                       **config.task_config
                       )
    # Create MPC controller.
    ctrl = make(config.algo,
                env_func,
                **config.algo_config
                )
    ctrl.reset()

    # Run the controller on the environment.
    test_env = env_func(gui=True, randomized_init=False)
    results = ctrl.run(env=test_env)
```
2. `linear_test_mpc.yaml`
```
output_dir: temp-data
tag: linear_mpc_test
seed: 0
algo_config:
  horizon: 20
  r_mpc:
    - 0.1
    - 0.1
  q_mpc:
    - 5.0
    - 0.1
    - 5.0
    - 0.1
    - 0.1
    - 0.1
  inertial_prop:
    - 0.027
    - 0.000014
  warmstart: True
  solver: qrqp
task_config:
  ctrl_freq: 20
  pyb_freq: 1000
  gui: false
  quad_type: 2
  info_in_reset: False
  randomized_init: False
  cost: quadratic
  task: traj_tracking
  inertial_prop:
    - 0.027
    - 0.000014
  constraints:
    - constraint_form: default_constraint
      constrained_variable: input
    - constraint_form: default_constraint
      constrained_variable: state
  done_on_violation: False
  disturbances: null
  task_info:
    trajectory_type: circle
    num_cycles: 1
    trajectory_plane: zx
    trajectory_position_offset:
      - 0.5
      - 0.0
    trajectory_scale: -0.5
  episode_len_sec: 5
  init_state:
    init_x: 0.0
    init_x_dot: 0.0
    init_z: 0.01
    init_z_dot: 0.0
    init_theta: 0.0
    init_theta_dot: 0.0

```

and then `cd ./experiments` and run
`python3 linear_mpc_test.py --task quadrotor --algo linear_mpc --overrides ./linear_mpc_test.yaml`

Let me know if you have any issues.
